---
description: 'TODO: Example with ELSER pipeline'
processors:
- set:
    field: sample_field
    value: "1"
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'
