apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: kube-system
  labels:
    k8s-app: elastic-agent

#apiVersion: v1
#automountServiceAccountToken: false
#kind: ServiceAccount
#metadata:
#  labels:
#    app.kubernetes.io/component: exporter
#    app.kubernetes.io/name: kube-state-metrics
#    app.kubernetes.io/version: 2.3.0
#  name: kube-state-metrics
#  namespace: kube-system
