---
description: Pipeline for cloudbeat findings
processors:
- set:
    field: ecs.version
    value: '8.6.0'
- set:
    field: rule.benchmark.posture_type
    value: 'kspm'
    description: 'Backward compatibility cloudbeat version < 8.7'
    if: ctx.rule?.benchmark?.posture_type == null
- set:
    field: orchestrator.cluster.id
    copy_from: cluster_id
    description: 'Backward compatibility cloudbeat version < 8.8'
    ignore_empty_value: true
    if: ctx.orchestrator?.cluster?.id == null
- script:
    lang: painless
    description: This script processor remove all empty fields from the findings document.
    source: |
        def removeEmptyFields(def map) {
            map.entrySet().removeIf(entry -> {
                def value = entry.getValue();
                if (value == null) {
                return true;
                }
                if (value instanceof String && value.isEmpty()) {
                return true;
                }
                if (value instanceof Map) {
                removeEmptyFields(value);
                return value.isEmpty();
                }
                return false;
            });
        }
        removeEmptyFields(ctx);
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: '{{{ _ingest.on_failure_message }}}'
